name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: [bootstrap, terraform]
    defaults:
      run:
        working-directory: ${{ matrix.stack }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: terraform fmt
        run: terraform fmt -check -recursive

      - name: terraform init (sem backend)
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate
